FROM php:8.3-fpm

# System deps
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    libicu-dev \
    libonig-dev \
    libxml2-dev \
    libpq-dev

# PHP extensions
RUN docker-php-ext-install \
    pdo_pgsql \
    zip \
    intl

# redis
RUN pecl install redis \
    && docker-php-ext-enable redis

# xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www

COPY . .

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY composer.json composer.lock ./
RUN composer install --no-dev --optimize-autoloader --no-interaction

RUN chown -R www-data:www-data /var/www

USER www-data

